name: schedule_mirea
description: A new Flutter project

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  excel: ^2.0.0-null-safety-3
  freezed_annotation: ^1.1.0 
  flutter: 
    sdk: flutter
  http: ^0.13.4
  path_provider: ^2.0.9
  sqflite: ^2.0.2
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  html: ^0.15.0
  shared_preferences: ^2.0.13

dev_dependencies:

  build_runner: ^2.1.4
  freezed: ^1.1.1
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
    # это временное решение. Этого асета здесь быть не должно
    # - 'assets/ИИТ_1 курс_21_22_весна.xlsx'