name: schedule_mirea
description: A new Flutter project

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  excel: ^2.0.0-null-safety-3
  freezed_annotation: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  path_provider: ^2.0.9
  flutter: 
    sdk: flutter

dev_dependencies:

  build_runner: ^2.1.4
  freezed: ^1.1.1
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  # это временное решение. Этого асета здесь быть не должно
  # - 'assets/ИИТ_1 курс_21_22_весна.xlsx'
