name: schedule_mirea
description: A new Flutter project

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  excel: ^2.0.0-null-safety-3
  freezed_annotation: ^1.1.0 
  flutter: 
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    # это временное решение. Этого асета здесь быть не должно
    - assets/ИИТ_1 курс_21_22_весна.xlsx